#!/bin/bash
set -eu

cd /devstack
. functions
. stackrc

# Workaround https://bugs.launchpad.net/tripleo/+bug/1285954
BM_POSEUR_REPO=https://github.com/tripleo/bm_poseur
BM_POSEUR_BRANCH=master
BM_POSEUR_DIR=/opt/stack/bm_poseur

HEAT_CONF_DIR=/opt/stack/heat

projects=$(declare | sed -n 's/^\(.*\)_REPO=.*/\1/p')

for project in ${projects}; do
    eval repo=\$${project}_REPO
    eval branch=\$${project}_BRANCH
    eval dir=$(git grep -h ${project}_DIR= | sed 's/.*=//')

    if [[ ${repo} =~ git.openstack.org ]]; then
        git_clone ${repo} ${dir} ${branch} || :
    fi
done
