#!/bin/bash

# Close extraneous file descriptors.
pushd /proc/self/fd >/dev/null
for FD in *
do
  case "$FD" in
  # Keep stdin/stdout/stderr
  [012])
    ;;
  # Nuke everything else
  *)
    eval exec "$FD>&-"
    ;;
  esac
done
popd >/dev/null

# If we were given a PORT environment variable, start as a simple daemon;
# otherwise, spawn a shell as well
if [ "$PORT" ]
then
  exec docker -d -H 0.0.0.0:$PORT 2>&1 >/dev/null
else
  docker -d 2>&1 >/dev/null &
  /opt/dockenstack/bin/wait-for-docker
fi
